### ISSUE TITLE
[App] Development for app : Sign in / Sign up / Sign out

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#18]
# Figma URL 
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=346%3A33

# Related Document 
[Service Process](https://docs.google.com/presentation/d/1CvEE_-A2uDF6PDoI6pZMdGaf2eXfIa5DBwyLHshmkWE/edit#slide=id.p)

You can check the service process in above document. 

This document currently defines the processes for Webapp access, Sign in, and Sign up.  The process for codreview is about to be added.

# Description 
The definition of the screen for Sign in, Sign up and Sign out has been completed.

**Comment by iamappple** [comment]
@aesopturtle @spock-recode We should be check for sign up process this work before. 

1. User click the button for sign up. (in RE-CODE site)
2. Agreement Terms and Condition (in RE-CODE site)
3. Github SSO (in Github site)
4. If completed Github SSO, move to RE-CODE app install page. (in Github site) 
 -> Like this
![image](https://user-images.githubusercontent.com/55983122/66806859-842f3d80-ef63-11e9-8175-072add371959.png)
5. User selected repository and installed RE-CODE app.
6. Move to RE-CODE site (and display our products information)

So process 4, 5 is this no problem? Can we? 

I think it would be nice if you could check this out.

**Comment by aesopturtle** [comment]
@iamappple This requires creating a github app which I have no idea how it works or how hard it is. I'll take a look and give you an update later.

**Comment by iamappple** [comment]
> @iamappple This requires creating a github app which I have no idea how it works or how hard it is. I'll take a look and give you an update later.

Okay. Then I'll design the screens that I need first on the RE-CODE site. Please write comments later.

**Comment by iamappple** [comment]
@aesopturtle I updated the service process document. Please check [this](https://docs.google.com/presentation/d/1CvEE_-A2uDF6PDoI6pZMdGaf2eXfIa5DBwyLHshmkWE/edit#slide=id.g64e6344eb6_0_5) document.

**Comment by iamappple** [comment]
And then i will improve the sign up screen today. :)

**Comment by iamappple** [comment]
@aesopturtle I have completed the design for Sign up and Sign in. Now only screens provided by our app are defined. If we need a screen when user go to Github, i will design it after it is analyzed. 

And the mobile version is made only in Korean. You can also create other language versions based on this.

Figma URL 
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=346%3A33

**Comment by aesopturtle** [comment]
@iamappple Please access https://re-code.io/landing for testing the login feature. Please note that a user can sign in without signing up first. It's an OAuth feature. That sign-up feature is actually unnecessary. There is one additional thing to be aware. If a user does not share his email address from his github account, the OAuth will not return his email address.

**Comment by iamappple** [comment]
@aesopturtle 
### Test Step 
I signed out of Github before testing this function.
(Chrome in Desktop)

1. Connected https://re-code.io/landing
2. Click the sign in button 
3. A new window opens. But the screen is empty with nothing on it.

![image](https://user-images.githubusercontent.com/55983122/67393006-8422e380-f5dc-11e9-8827-ae6aba17e17a.png)

Is phenomenon number 3 normal?

**Comment by iamappple** [comment]
@aesopturtle 
I tested the connection on PC and Mobile chrome and Safari browser.
(https://re-code.io/landing)

### Test

- **When connected from Chrome browser on PC**: OK

- **When connect from the Chrome browser on PC and change to the mobile version**: OK.

- **When connect from the Safari browser on my PC** : blank screen 

![image](https://user-images.githubusercontent.com/55983122/67394215-c77e5180-f5de-11e9-9ce1-622bc4ee0dc5.png)

- **Access from the mobile phone (iPhone X) Chrome** : blank screen

![image](https://user-images.githubusercontent.com/55983122/67393800-1081d600-f5de-11e9-8a54-43de92311fbf.png)

- **Access from the mobile phone (iPhone X) safari** : blank screen

![image](https://user-images.githubusercontent.com/55983122/67393814-18da1100-f5de-11e9-8162-fa117b245dad.png)
