### ISSUE TITLE
[App] Wireframe for app : PRs

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#21]
# Figma URL 
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=190%3A269

**Comment by ryancho** [comment]
Nothing to do say
살펴보았습니다. 이견없습니다.

**Comment by iamappple** [comment]
@aesopturtle @spock-recode I have completed the design and definition of the PR page. First of all, please check the currently produced screen and give me your opinion.  I will make a mobile version after I finally apply them.

**Comment by iamappple** [comment]
@spock-recode @aesopturtle We end this issue because we've decided to implement this as an open source.
