### ISSUE TITLE
Sales action [Plan]

### ISSUE THREAD

**Issue by ryancho** [re-code-io/app#22]
- [x] First Sales Starting
Step: After Payment
-receipt
[Result](https://mail.google.com/mail/u/3/?tab=wm&ogbl#inbox/FMfcgxwDrlVmnKQCMtfJDmFpCzwCpTDq)
-NDA/privacy
[Result](https://docs.google.com/forms/u/3/d/1t1VDt48oULieaRidJO2mg_X8ABm3E4xtG_4INeMYBQE/edit?usp=drive_web)
a.NDA
[Result](https://www.notion.so/NDA-8ff77d7185834647ba09dbb71f7b020e)
b.Terms of Serivce
[Result](https://www.notion.so/961e7a115043448d8fd66113225f9581)
c.Privacy Policy
[Result](https://www.notion.so/v-20191001-e0047061ddbc41f09a0379430dd92c4e)
-How to make first PR (code review guide)
[Result](https://docs.google.com/spreadsheets/d/1mlj0o1AHmDVn_lpgtsJA70Mrtk5-dA6j9PxNJMNvv0o/edit#gid=1897421658)

- [x] Contact Sales Point
-SmallTeam
[Result](https://docs.google.com/spreadsheets/d/1dk-p-KEkDN0uK8aXYMqnpv2wx3xzrNiFmrpAjSt0oSg/edit#gid=1573371342) J008
-Individual
[Result](https://docs.google.com/spreadsheets/d/1dk-p-KEkDN0uK8aXYMqnpv2wx3xzrNiFmrpAjSt0oSg/edit#gid=1573371342) J008

- [x] Sales Step Process
**::Side:Reviewee**
**Step: Gathering Reviewee**
-Guide of code review
[Result](https://docs.google.com/document/d/1AIXXzQECY115kNp1iTW5qqeYxML_ZpEqTJ1axnbQFfA)
-Product Introduction
[Result](https://docs.google.com/presentation/d/1f4e_pVVyY3wTLWvnI7y9QxEqjsKj4meIgoaF4AF9U5s)
-FAQ
[Result](https://docs.google.com/document/d/1ZvLHQI7OOhfPtEvxbZ6oLa2gDxEOruBLg_qjBYaqJNc)
**Step: Apart Reviewee type**
[Result](https://docs.google.com/spreadsheets/d/1mlj0o1AHmDVn_lpgtsJA70Mrtk5-dA6j9PxNJMNvv0o/)
**Step: Before Payment**
-Apply to review
[Result](https://docs.google.com/forms/d/1hQneCXJMyVMQNHr-0ydgzSZHsOMvFwtvPe4i0Tw-2iw/edit) 
-Apply to payment
[Result](https://docs.google.com/forms/u/3/d/1KyJ730_8tTgPyefTAXqiPTMKwcR5V44bNzWv4XJRN5M/edit?usp=drive_web)
*Apply to review for tillie
[Result](https://docs.google.com/forms/d/1mcIZ9HT1MhdlvqeUw0WMTyXTUIudHCK04ENH1c1ALuQ/edit)
**Step: After Payment**
[Result](https://mail.google.com/mail/u/3/#sent/QgrcJHsTmbWmgFTprcLgrHWmNcQVjSwmJsL)
**Step: Ongoing Service**
**::Side:Reviewer**
[Result](https://docs.google.com/spreadsheets/d/1mlj0o1AHmDVn_lpgtsJA70Mrtk5-dA6j9PxNJMNvv0o/edit#gid=585476891)
- [x] Reviewer Interview/Question [plan]
[Result](https://docs.google.com/spreadsheets/d/1mlj0o1AHmDVn_lpgtsJA70Mrtk5-dA6j9PxNJMNvv0o/edit#gid=995406894)
- [x] Reviewee Individual Customer Contact [plan]
[Result](https://docs.google.com/spreadsheets/d/1mlj0o1AHmDVn_lpgtsJA70Mrtk5-dA6j9PxNJMNvv0o/edit#gid=438657159)
- [x] Sales Overview
RevieweeFunnel 
[Result](https://docs.google.com/spreadsheets/d/1dk-p-KEkDN0uK8aXYMqnpv2wx3xzrNiFmrpAjSt0oSg/edit#gid=857762947)
ReviewerFunnel 
[Result](https://docs.google.com/spreadsheets/d/1O4aQZflrtLp9WZidwjrkiKf4XuGI1d9azagDwSHJFAE/edit#gid=1522367510)
SalesTrackRecord
[Result](https://docs.google.com/spreadsheets/d/1O4aQZflrtLp9WZidwjrkiKf4XuGI1d9azagDwSHJFAE/edit#gid=1573371342)
- [x] Marketing Dashboard (all DB)
[Result](https://docs.google.com/spreadsheets/d/1mlj0o1AHmDVn_lpgtsJA70Mrtk5-dA6j9PxNJMNvv0o/edit#gid=338488060)
- [x] Marketing Dashboard (Plan)
[Result](https://docs.google.com/spreadsheets/d/1O4aQZflrtLp9WZidwjrkiKf4XuGI1d9azagDwSHJFAE/edit#gid=1573371342)

**Comment by spock-recode** [comment]
리뷰어 질문지와 심사기준에 대해,
리뷰어들의 Check List 9가지를 기준으로 설문지가 작성되어 심사를 통해 Level을 정하고 github id를 받는것이 좋겠습니다.
그리고 domain 지식의 경우에는 검증할 방법이 마땅히 없기 때문에, 이력을 제시하는 것으로 확인해야 겠습니다.

**Check List**
1. 로직
2. 알고리즘
3. 재사용성
4. 확장성
5. 성능
6. 보안
7. 적절한 라이브러리 사용
8. 디자인 패턴
9. 잠재적 버그

**Comment by ryancho** [comment]
@spock-recode 
NDA/privacy

**Comment by spock-recode** [comment]
> @spock-recode
> https://docs.google.com/forms/d/1t1VDt48oULieaRidJO2mg_X8ABm3E4xtG_4INeMYBQE/edit
> 
> 발주자에게 보낼 NDA/Privacy입니다.
> 검토 바랍니다.
> 
> 겁토내용:
> :: 동의화면등이 없어 보이지는않나요
> 그렇다면 대안은 ?
> :: 이용약관 내용은 크몽(양면서비스)을 수정했습니다.

현재 수준에서 우리가 할 수 있는 최선이라 생각합니다.

**Comment by ryancho** [comment]
@reviewer-recode 
test noti

**Comment by ryancho** [comment]
@reviewer-recode 
test noti2

**Comment by ryancho** [comment]
@reviewer-recode 
test phone noti3

**Comment by spock-recode** [comment]
@reviewer-recode test test test

**Comment by ryancho** [comment]
@reviewer-recode mention test

**Comment by ryancho** [comment]
@reviewer-recode phone noti

**Comment by ryancho** [comment]
@reviewer-recode  notititititititi !!

**Comment by ryancho** [comment]
@reviewer-recode noti

**Comment by ryancho** [comment]
@reviewer-recode cool

**Comment by ryancho** [comment]
@reviewer-recode hoho

**Comment by ryancho** [comment]
@spockwoz please check this " Reviewee Individual Customer Contact. "
