### ISSUE TITLE
[App] UI/UX decision

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#23]
This is an issue for discussion of our service screen. @aesopturtle @ryancho @spock-recode 

If you have an opinion and you have one, please register it as a comment on this ticket. And you can see the original Figma screen through the URL of each screen.

* The main screen excluded the decision because we all voted.

## Sign in / Sign up 
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=346%3A33

![image](https://user-images.githubusercontent.com/55983122/66730725-722f9b00-ee8e-11e9-9c29-ac0454013c88.png)

## How it works 
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=171%3A151

![image](https://user-images.githubusercontent.com/55983122/66730588-b53d3e80-ee8d-11e9-8c84-bae0ae43ab3f.png)

## Pricing 
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=179%3A224

![image](https://user-images.githubusercontent.com/55983122/66730619-daca4800-ee8d-11e9-80cb-e5b818bb1d55.png)

## PRs
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=190%3A269

![image](https://user-images.githubusercontent.com/55983122/66730658-0baa7d00-ee8e-11e9-89ab-8c9d2f7e4ddc.png)

**Comment by iamappple** [comment]
Please check this issue.  @aesopturtle @ryancho @spock-recode

**Comment by spock-recode** [comment]
## Prcing
- 개인용/기업용을 Tab으로 구분해서 보여주는 것이 어떨까 합니다.

## PRs
- 나(또는 팀)의 PR을 Summary 형태로 상단에 보여주는 것이 좋을 것 같습니다.
- Story -> "나(또는 팀)이 요청한 PR의 진행상황을 한 눈에 보고 싶다.

**Comment by iamappple** [comment]
@spock-recode  상기 코멘트에 대한 질문입니다. 

**1.  Pricing** 
탭 구분을 하는 것은 좋은 아이디어로 생각됩니다. 특히나 모바일을 고려했을때는요. 

근데 이렇게되면 디폴트로 보여지는 탭 외의 요금제는 유저가 클릭을 해야만 보여지게 되는 것이 조금 걸리네요. 

이 부분 고려해서 다시 한번 생각해봐주세요. 


**2. PRs** 
Story 부분은 잘 이해가 안가는데, 혹시 참고할만한 레퍼런스가 있으실까요?

**Comment by spock-recode** [comment]
> @spock-recode 상기 코멘트에 대한 질문입니다.
> 
> **1. Pricing**
> 탭 구분을 하는 것은 좋은 아이디어로 생각됩니다. 특히나 모바일을 고려했을때는요.
> 
> 근데 이렇게되면 디폴트로 보여지는 탭 외의 요금제는 유저가 클릭을 해야만 보여지게 되는 것이 조금 걸리네요.
> 
> 이 부분 고려해서 다시 한번 생각해봐주세요.
> 
> **2. PRs**
> Story 부분은 잘 이해가 안가는데, 혹시 참고할만한 레퍼런스가 있으실까요?

1. 탭으로 보여져야 요금이 차이가 나는 이유가 구분이 되고 간단히 인지할 수 있으리라 보입니다.
2. 내(또는 팀)이 최근 요청한 PR들의 진행상황을 보여주면 될 것 같습니다. 이용자의 PR을 한눈에 볼 수 있는 페이지가 없으니 당장은 PRs 페이지를 활용하자는 의견입니다.

**Comment by iamappple** [comment]
@spock-recode 상기 내용 반영 작업 진행하도록 하겠습니다.

**Comment by iamappple** [comment]
@spock-recode @aesopturtle I finished Pricing screen design. Please check it out figma file. 
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=179%3A224

**Comment by ryancho** [comment]
1.Sign in / Sign up
a.Contract Service
Terms of Service
Privacy
NDA
가 들어가야하는데 가입단계에서 받는것을 좋을것같습니다. 
[들어갈내용들](https://docs.google.com/forms/d/1t1VDt48oULieaRidJO2mg_X8ABm3E4xtG_4INeMYBQE)

b.Text
레파지토리 -> 레포지토리 [(위키피디아에서는 레포지토리사용)](https://ko.wikipedia.org/wiki/%EC%A0%80%EC%9E%A5%EC%86%8C)

**Comment by ryancho** [comment]
@spockwoz prcing에 200만원 모델이 들어가야할것같은데. 링크 공유가 apple님에게 되었나요

**Comment by iamappple** [comment]
> 1.Sign in / Sign up
> a.Contract Service
> Terms of Service
> Privacy
> NDA
> 가 들어가야하는데 가입단계에서 받는것을 좋을것같습니다.
> [들어갈내용들](https://docs.google.com/forms/d/1t1VDt48oULieaRidJO2mg_X8ABm3E4xtG_4INeMYBQE)
> 
> b.Text
> 레파지토리 -> 레포지토리 [(위키피디아에서는 레포지토리사용)](https://ko.wikipedia.org/wiki/%EC%A0%80%EC%9E%A5%EC%86%8C)

1. 해당 내용을 반영하기 위해서는 프로세스를 좀 변경해야겠네요. 이 부분은 작업 완료되는 대로 다시 공유 드릴게요. 

2. 한글 기준 레포지토리로 변경 적용 하도록 하겠습니다. 

3. 200만원 모델에 대해서는 공유가 안되었습니다. 상세 내용 댓글 남겨주세요.

**Comment by iamappple** [comment]
@@ryancho @spock-recode @aesopturtle   추가적인 의견이 있다면 금일 오후 2시까지 이 이슈에 코멘트로 남겨주세요. 
If you have any further comments, please comment on this issue by 2:00 p.m. today.

상기 의견에 대해서는 현재 디자인 반영 작업 중에 있으며 반영 완료 후에는 별도 공유하도록 하겠습니다. 
I am currently working on the design and will share the after design.

@ryancho 200만원 모델이 포함될 위치(개인/기업)와 안내 사항에 대해서 본 이슈에 코멘트로 남겨주세요.

**Comment by spock-recode** [comment]
200만원은 월 정액 요금인데, 아직 확정된 사항이 아닙니다. 테스트 중이고, 포맷이 크게 다른 것이 아니기 때문에 개발 후 런칭하는 시기에 적용하는 것으로 가겠습니다.

**Comment by aesopturtle** [comment]
I have a question about the PR list.
That list is a list of PRs of a specific user, right?
Or is it a list of PRs of a specific organization?
I see that the title says "My Code Review" but there are many reviewees under the PR list.
And if they are PRs for a specific user, why do we need to hide/blur the title for private PRs?

Another issue is about the PR statuses.
I think we could make it more obvious by putting them into separate lists or columns (like a sprint board) and having an option to toggle a view between a unified list and separate lists/columns.
Using an icon to identify the status is a bit confusing for me since it looks more like a PR type than a PR status.
What do you think?

**Comment by iamappple** [comment]
> I have a question about the PR list.
> That list is a list of PRs of a specific user, right?
> Or is it a list of PRs of a specific organization?
> I see that the title says "My Code Review" but there are many reviewees under the PR list.
> And if they are PRs for a specific user, why do we need to hide/blur the title for private PRs?
> 
> Another issue is about the PR statuses.
> I think we could make it more obvious by putting them into separate lists or columns (like a sprint board) and having an option to toggle a view between a unified list and separate lists/columns.
> Using an icon to identify the status is a bit confusing for me since it looks more like a PR type than a PR status.
> What do you think?

First of all, the PRs screen needs to be changed. We also want to show user the current status of other people's code views in your own PRs and RE-CODE on the page. 
To do so, I am going to change that UI. 

And your idea is very good. I'll consider the same UI as the Sprint board.
