### ISSUE TITLE
[Admin] Implement sign-in with Google

### ISSUE THREAD

**Issue by aesopturtle** [re-code-io/app#28]
Implement the sign-in page for the admin project.
The sign-in should have the following characteristics:
1. sign-in with Google
2. only allow email addresses under ReCode organization (re-code.io domain)

Design: https://www.figma.com/file/miRQYWwKQFkv0SbL3opjl2/Backoffice?node-id=18%3A1

**Comment by aesopturtle** [comment]
@iamappple Yeah. https://admin-re-code-io.firebaseapp.com

**Comment by iamappple** [comment]
@aesopturtle @spock-recode I tested this. Completed.
