### ISSUE TITLE
Create for App & Admin gantt 

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#30]
## Gantt 
[Link](https://docs.google.com/spreadsheets/d/1QzgU_Q99GKbz25ke8cHxxe23aqIFAE6d75gD9SVa2no/edit#gid=2048004259)

**Comment by iamappple** [comment]
I making a Gantt Chart for App & Admin right now. So I need your opinion on our schedule in the future. 

Please check the gantt chart.  [Link](https://docs.google.com/spreadsheets/d/1QzgU_Q99GKbz25ke8cHxxe23aqIFAE6d75gD9SVa2no/edit#gid=2048004259)

Now, 

1. The test schedule has not yet been included. 
2. Currently, the app schedule and administrator schedule are set separately. 

I wonder if you think this schedule is efficient. 
If we proceed like this, we will have to schedule separate test for apps and admin site. 

Or is it better to work with the same app and the admin screen?

For example

When creating a sign up for an app, work on the Users screen of the admin site. 
Then test and complete.  Then start the next work. 


What do you think?


@aesopturtle

**Comment by aesopturtle** [comment]
@iamappple I think the development for app and admin should go together for related features. However, for testing, we can do it separately and focus on the app first. In fact, we can even use the admin site to help with the testing of the app. For example, if we are working with the sign-up page for the app, we can use the admin site to check if the user appears in the list. If not, we can then check against the database to see if a user data has been saved. This actually tests the feature on the admin site at the same time.

What do you think?

**Comment by iamappple** [comment]
> @iamappple I think the development for app and admin should go together for related features. However, for testing, we can do it separately and focus on the app first. In fact, we can even use the admin site to help with the testing of the app. For example, if we are working with the sign-up page for the app, we can use the admin site to check if the user appears in the list. If not, we can then check against the database to see if a user data has been saved. This actually tests the feature on the admin site at the same time.
> 
> What do you think?

I agree with you. Okay. Then I'll try to reschedule the app so that the admin can go along with it.
