### ISSUE TITLE
Improved user story

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#31]
For App & Admin stie MVP version

# Document 

[Link](https://docs.google.com/spreadsheets/d/1QzgU_Q99GKbz25ke8cHxxe23aqIFAE6d75gD9SVa2no/edit#gid=0) 

I wrote it on the MVP tab. 

User stories are written around functions. More details will be defined in the Wireframe & Design file.

**Comment by iamappple** [comment]
@aesopturtle @spock-recode Please check this issue. This is a user story written for the MVP version.

**Comment by spock-recode** [comment]
LGTM
