### ISSUE TITLE
PG 정보 전달 

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#38]
1. 서비스에 적용할 PG사 정보를 전달해주세요. 
2. 우리 사이트에서 결제를 제공하는데, 전자상거래 관련해서 자격득실 같은 것이 필요할까요? 확인이 필요할 것 같아요.

**Comment by spock-recode** [comment]
@ryancho UI 제작을 위한 참고 자료 좀 전달 부탁합니다.

**Comment by ryancho** [comment]
1. 부트페이
id lion@re-code.io / tkdlvks!47a 
사이트 https://admin.bootpay.co.kr/receipt?s=1
  


2.

**Comment by iamappple** [comment]
> * 부트페이 (다날PG)
>   id [lion@re-code.io](mailto:lion@re-code.io) / tkdlvks!47a
>   사이트 https://admin.bootpay.co.kr/receipt?s=1
> * 통신판매업자등록을 말하시는건가요?
>   필요합니다. 다만 런칭후 한달안에 하면됩니다.
>   다만, 지금 등록할려고해도 등록안됩니다. 사이트가 개발중이라서 신청조차 안되요
>   런칭이후 pg정식계약 2주소요, 통신판매업자등록까지추가1주일 정도 예상하면되빈다.


전달 감사합니다. 
금일 밤에 확인하도록 할게요.
