### ISSUE TITLE
[App] Create how-it-works page

### ISSUE THREAD

**Issue by aesopturtle** [re-code-io/app#39]
https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=171%3A151

**Comment by iamappple** [comment]
@aesopturtle @spock-recode I tested this screen of desktop and mobile version. No problem. Thanks @aesopturtle. But how i check Korean version? We need a Korean version first. right @spock-recode ?

**Comment by iamappple** [comment]
@aesopturtle I can not check it my phone (iPhone X / Safari / Chrome) Please check again.
