### ISSUE TITLE
[Backoffice] Wireframe : Payment

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#44]
### Figma 
https://www.figma.com/file/miRQYWwKQFkv0SbL3opjl2/Backoffice?node-id=126%3A0 

### Description
This is the screen to view the payment list. We can search and check the payment status and information on this screen. There is no function to manage here. The payment management function will use the admin page provided by PG.

**Comment by iamappple** [comment]
@spock-recode 관리자 사이트에 대한 화면입니다. 위의 경로로 확인하셔도 되고, 피그마 앱으로 직접 접속할 경우에는 Project_RE-CODE > Backoffice 파일의 Payment 화면을 확인하면 됩니다.

**Comment by spock-recode** [comment]
확인했습니다~ 특이사항 없습니다.
