### ISSUE TITLE
[Test] App : Sign up / Sign in / Sign out

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#48]
### Test 
I tested my laptop and mobile browser. (Chrome, Safari) 

- [x] 1. Sign up by github account
- [x] 2. Sign in 
- [ ] 3. Sign out

**Comment by iamappple** [comment]
@aesopturtle 
I've logged in, but this area doesn't change. 

- Laptop version
![image](https://user-images.githubusercontent.com/55983122/68529516-ec92f400-0342-11ea-9e75-2bceeb30210b.png)

- Mobile version
![image](https://user-images.githubusercontent.com/55983122/68529526-f583c580-0342-11ea-8e72-bd17d191851d.png)


You can check the screen after logging in at Figma [file](https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=346%3A33)

![image](https://user-images.githubusercontent.com/55983122/68529561-4398c900-0343-11ea-84cb-18c7b50c7956.png)

**Comment by iamappple** [comment]
### Check for sign up 
@aesopturtle  I sign up with my github account. Can you check that I'm a member?

**Comment by aesopturtle** [comment]
@iamappple Sorry for such a late reply. Please try the sign-up/in feature again. Many things have been changed.

**Comment by aesopturtle** [comment]
@iamappple I saw that the ticket has been assigned to both you and me. Is it ready for me to work on? I have removed myself from being an assignee. Please assign it to me (only me) again when this ticket is ready for me to work on. Having multiple assignees are a bit confusing.

**Comment by iamappple** [comment]
> @iamappple I saw that the ticket has been assigned to both you and me. Is it ready for me to work on? I have removed myself from being an assignee. Please assign it to me (only me) again when this ticket is ready for me to work on. Having multiple assignees are a bit confusing.

Okay i will create new issue. 
And close this issue.
