### ISSUE TITLE
[App] Add Korean translation

### ISSUE THREAD

**Issue by aesopturtle** [re-code-io/app#51]

**Comment by iamappple** [comment]
Korean version test 

- [ ] Main 
- [ ] Sign up
- [ ] Sign in
- [ ] How it works
- [ ] Pricing

**Comment by iamappple** [comment]
@aesopturtle  I can't see the payment order and order completed screen. I will make another issue about that. That is because it is a different error. 
In this issue, he only wrote about the application of the Korean version.

**Comment by iamappple** [comment]
@aesopturtle  
**Pricing > Individual, Corporation : Request popup** 

![image](https://user-images.githubusercontent.com/55983122/69250870-d19e6a80-0bf3-11ea-9228-ea7940c6903c.png)

![image](https://user-images.githubusercontent.com/55983122/69250919-e24ee080-0bf3-11ea-81ba-c26a9f90b0c4.png)

You can check the Korean version screen in this Figma.

https://www.figma.com/file/6zH2mFVA3Ol2agEbZ1EGq3/Ver-02?node-id=466%3A85
