### ISSUE TITLE
[Test] Mobile version

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#53]
### Test 
iPhone X chrome, safari  (all current version) 

We have to improve mobile version. 
I'll write comment in this issue check point.

**Comment by iamappple** [comment]
@aesopturtle  
### Test Step 
1. Open the landing main page by my phone Safari, Chrome 
2. And Scroll right in screen 

![image](https://user-images.githubusercontent.com/55983122/68681167-447d6500-05a6-11ea-965d-8001f52fdd07.png)

3. As shown above, the right part of the pattern is visible.

### Improvement
I think we don't provided scroll right and left in mobile version. 
And i attached mobile version SVG file. Please check this file.


[mobile_bottom pattern.svg.zip](https://github.com/re-code-io/app/files/3836690/mobile_bottom.pattern.svg.zip)

**Comment by iamappple** [comment]
@aesopturtle 
### Test 
1. Open the landing main page by my phone Safari, Chrome
2. And touch hamburger menu on left top

![image](https://user-images.githubusercontent.com/55983122/68681914-9c689b80-05a7-11ea-9cc5-e41b3caf7c6a.png)


### Improvement 
I think we can get rid of the RE-CODE symbol in red squares.

**Comment by iamappple** [comment]
> @aesopturtle
> 
> ### Test
> 1. Open the landing main page by my phone Safari, Chrome
> 2. And touch hamburger menu on left top
> 
> ![image](https://user-images.githubusercontent.com/55983122/68681914-9c689b80-05a7-11ea-9cc5-e41b3caf7c6a.png)
> 
> ### Improvement
> I think we can get rid of the RE-CODE symbol in red squares.

I checked this screen. Thanks.

**Comment by iamappple** [comment]
> @aesopturtle
> 
> ### Test
> 1. Open the landing main page by my phone Safari, Chrome
> 2. And touch hamburger menu on left top
> 
> ![image](https://user-images.githubusercontent.com/55983122/68681914-9c689b80-05a7-11ea-9cc5-e41b3caf7c6a.png)
> 
> ### Improvement
> I think we can get rid of the RE-CODE symbol in red squares.

I checked this screen by chrome, safari from laptop mode and mobile phone(iPhone X)
But the same thing is still happening. 

![image](https://user-images.githubusercontent.com/55983122/69244428-45d31100-0be8-11ea-8360-a4e9585fde71.png)

**Comment by aesopturtle** [comment]
@iamappple Please try refreshing the page. You should be able to see the fixed version now.

**Comment by iamappple** [comment]
> @iamappple Please try refreshing the page. You should be able to see the fixed version now.

Yeah i checked this screen. Thanks
