### ISSUE TITLE
Launch Subscription

### ISSUE THREAD

**Issue by aesopturtle** [re-code-io/app#6]
Implement UI to allow a user to subscribe for a notification when re-code is launched. Use firebase hosting for UI site hosting and use cloud firestore to store data.

- [x] Setup project structure
- [x] Apply themes with Angular Material Theme Engine
- [x] Create mobile layout for email subscription
- [x] Create desktop layout for email subscription
- [x] Implement firebase hosting to the Web project
- [x] Implement data store with Cloud Firestore
- [x] Implement form validation

**Comment by spock-recode** [comment]
![image](https://user-images.githubusercontent.com/55256260/65873045-02fd7580-e3bd-11e9-8f7d-03427a5ee301.png)
Could you please make that checkbox to required?

**Comment by aesopturtle** [comment]
@iamappple The changes have been deployed to https://re-code-io.firebaseapp.com.
Please note that the button color cannot be easily changed at the moment since it follows the material theme engine.
I will come back and customize it later.
