### ISSUE TITLE
Change the teaser site style 

### ISSUE THREAD

**Issue by iamappple** [re-code-io/app#8]
# Figma file 
https://www.figma.com/file/T2o78Qs9xxehsPu9Zq8iKD/Teaser?node-id=0%3A1

# Description
We need change some part in our teaser site.  

1. Delete our service name and insert B.I image 
2. Added background in user input form. 

![image](https://user-images.githubusercontent.com/55983122/65878030-0b0ee280-e3c8-11e9-9cc4-5c2f54a31f5e.png)
 

Sorry. I can not attach the file.

**Comment by aesopturtle** [comment]
- [x] Center the content area.
- [ ] Increase spacing between radio buttons.
- [ ] Replace text-based logo with images.
- [ ] Add white background to form area.

**Comment by aesopturtle** [comment]
@iamappple The changes have been deployed to https://re-code-io.firebaseapp.com.
Please note that the colors of the controls (radio, checkbox, and button) on the white background follow the theme engine and cannot be easily customized.
I will come back and customize them later.

**Comment by iamappple** [comment]
Please change the size of this text a little bit larger on mobile version.

![image](https://user-images.githubusercontent.com/55983122/65936579-06920a80-e458-11e9-8521-44e53c295e15.png)


Looks like this

![image](https://user-images.githubusercontent.com/55983122/65936712-7dc79e80-e458-11e9-88d8-1487e5651bea.png)

**Comment by iamappple** [comment]
@aesopturtle  And please change the page title. -> RE: {CODE};

**Comment by aesopturtle** [comment]
@iamappple For point 3, I'm not sure if that can be achieved since it's the browser's behavior which is based on the input font size. Based on the design, the font size is so small that Safari will zoom automatically. However, I have tried using the fix suggested by @spock-recode. Please try again to see if the issue is fixed.

**Comment by iamappple** [comment]
@aesopturtle Can you change the desktop version text? 
Like this. 
![image](https://user-images.githubusercontent.com/55983122/65945120-3ba95780-e46e-11e9-90b7-c73a134d2948.png)

I think it would be better to come out of the mobile version only as it is now.

**Comment by aesopturtle** [comment]
@iamappple It's probably not possible to force a line break on mobile but not on a desktop. If we don't insert a line break, it won't look like what you asked for for the mobile screen.

**Comment by iamappple** [comment]
@aesopturtle  

# 1. Change head copyright text 
* (now) 국내외 Top Class 전문가의 코드 리뷰가 시작됩니다.
Github를 통한 간편하고 완벽한 코드 리뷰를 경험해보세요.

* (Change) 국내외 Top Class 전문가의 코드 리뷰가 시작됩니다.
간편하고 완벽한 코드리뷰를 경험해보세요.

You can check the figma file.  
https://www.figma.com/file/T2o78Qs9xxehsPu9Zq8iKD/Teaser?node-id=0%3A1

Desktop 
![image](https://user-images.githubusercontent.com/55983122/65948479-503d1e00-e475-11e9-90f5-4aaf5fd29c48.png)
 
Mobile version
![image](https://user-images.githubusercontent.com/55983122/65948514-61862a80-e475-11e9-9318-9cca23b030f7.png)
 

# Open graph tag setting 
* Type : website
* Title : RE: {CODE};
* Description : 클래스 전문가의 완벽한 코드리뷰가 시작됩니다.
* image file (I will send this image file by slack) 
![image](https://user-images.githubusercontent.com/55983122/65949833-e6724380-e477-11e9-964a-f29f09c691f7.png)
 * URL : re-code.io

**Comment by aesopturtle** [comment]
@iamappple Please check again. The OG information may not appear until `re-code.io` points to the server.
